name: Automatic Production Deployment (CD)

on:
  push:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4

        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

  deploy-to-production-automatic:
    needs: build-and-test
    runs-on: ubuntu-latest

    environment: production-auto

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Automatic deployment
        run: |
          echo "AUTOMATIC DEPLOYMENT"
          echo "Version: $(git rev-parse --short HEAD)"